# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Kodethon Blog" 
email: kodethon.cde@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is the official blog for the Kodethon Cloud Development Environment.
  Code better. Code Together.
baseurl: "" # the subpath of your site, e.g. /blog
#baseurl: "/kodethon-blog" # the subpath of your site, e.g. /blog
#url: "https://blog.kodethon.com" # the base hostname & protocol for your site, e.g. http://example.com
url: "https://kodethon.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: martin_velez_
github_username:  martinvelez
#permalink: date # default
permalink: /:year/:month/:day/:title.html
disqus: kodethon
bitly_kodethon_url: http://bit.ly/2pf1YBI-kodethon
bitly_blog_url: http://bit.ly/2pAiWrd-kodethon 
bitly_forum_url: http://bit.ly/2o1WB8P-kodethon 

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
sass:
  sass_dir: _sass

# Collections
collections:
  newsletters:
    output: true
    permalink: /:collection/:path.html
  tutorials:
    output: true
    #permalink: /:collection/:path.html

# Author details.
authors:
  martin_velez:
    name: Martin Velez 
    email: marvelez@ucdavis.edu
    twitter: http://twitter.com/martin_velez_
  matt_l:
    name: Matt L
    email: matt@kodethon.edu

